# Generated by Django 4.2.7 on 2023-11-09 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="rate",
            new_name="stars",
        ),
    ]
